"""Assemble the jury-facing bundle in `final_deliverables/`.

The brief (§10) asks for four things a reviewer should not have to hunt for:
the three CSV exports and the solution diagram. They exist elsewhere in the
repository — the CSVs in the outputs folder, the diagram under `docs/` — so
this collects them in one place.

Copied by the pipeline on every run rather than by hand, because a hand-copied
deliverable is a deliverable that goes stale: the CSVs would keep the numbers
of whichever run someone last remembered to copy. A test asserts the copies
match their sources byte for byte.
"""

from __future__ import annotations

import shutil
from pathlib import Path

# (source relative to the repo root, name in the bundle, what it is)
ITEMS = [
    ("{out}/nodes_roles.csv", "nodes_roles.csv",
     "One row per account: role, confidence, cluster, review priority, evidence."),
    ("{out}/clusters.csv", "clusters.csv",
     "One row per cluster: size, seed count, internal turnover, top accounts, hypothesis."),
    ("{out}/top_nodes.csv", "top_nodes.csv",
     "The ranked shortlist: who to review first, with a written reason for each."),
    ("docs/diagram.md", "diagram.md",
     "Solution diagram: data -> metrics -> roles -> interface."),
]

INDEX = """# Final deliverables

**Track 2 — Finances.** HackAlem AI: *Money Graph — reconstructing the
financial structure of an organized group from a transaction network.*

Everything the brief asks to be handed over (§10), in one folder.

> Generated by `python run.py` on every run — do not edit by hand. The copies
> here are byte-identical to the originals, and a test enforces that.

| File | What it is |
|---|---|
{rows}

## The other two deliverables

| | Where |
|---|---|
| **Repository** — pipeline and interface source | the repository this folder sits in |
| **README** — how to run it, role criteria, limitations, scaling | [`README.md`](../README.md) (Русский) · [`README.en.md`](../README.en.md) · [`README.kk.md`](../README.kk.md) |

## Demo

🎬 **[Demo video](https://drive.google.com/file/d/12QR4d0btDiXnJPrcPog81NrcqCMhTWoe/view?usp=sharing)**

The brief also asks for a **live** demo: *"during the demo the jury
names a gid — the team finds it on the map and shows its links"*. A recording
cannot answer an account the jury picks on the spot, so the video complements
the live run rather than replacing it.

The script for the live demo is [`../docs/demo_script.md`](../docs/demo_script.md)
— with the real account numbers, and a fallback if anything refuses to start.

To run it:

```bash
./agent_run.sh --use-existing      # opens the interface on these results
```

## Reproducing these files

```bash
./agent_run.sh --offline           # no API key needed; same roles, same ranks
```

The pipeline is deterministic and the agent-chosen thresholds are committed in
`config.calibrated.yaml`, so the numbers in these CSVs come back identical.
"""


def publish(root: str | Path, out_dir: str | Path,
            folder: str = "final_deliverables") -> tuple[Path, list[str]]:
    """Copy the bundle into `folder`. Returns (path, names copied)."""
    root, out_dir = Path(root), Path(out_dir)
    dest = root / folder
    dest.mkdir(parents=True, exist_ok=True)

    copied, rows = [], []
    for template, name, description in ITEMS:
        src = root / template.format(out=out_dir.name) \
            if "{out}" in template else root / template
        if "{out}" in template:
            src = out_dir / Path(template.format(out=out_dir.name)).name
        if not src.exists():
            continue
        shutil.copy2(src, dest / name)
        copied.append(name)
        rows.append(f"| [`{name}`]({name}) | {description} |")

    (dest / "README.md").write_text(INDEX.format(rows="\n".join(rows)),
                                    encoding="utf-8")
    return dest, copied
