"""Phase 0 data profiling (guideline §3).

Prints a report and writes ``outputs/profile_report.md``. Every fact the brief
announces is checked against the actual files; a mismatch is reported loudly
rather than raised, because the point of this stage is to *learn* what the data
really looks like before any threshold is chosen.

The percentile tables at the end are what ``config.yaml`` thresholds are derived
from, so this module must run before any threshold is touched.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd

from .io import Dataset, load_dataset

# Facts announced in the brief and in data/README.md. Checked, not trusted.
EXPECTED = {
    "n_nodes": 2248,
    "n_edges": 3119,
    "n_tx": 4840,
    "n_seeds": 81,
    "hop_distribution": {0: 81, 1: 472, 2: 462, 3: 789, 4: 444},
    "total_turnover_kzt": 365_890_012,
    "n_truncated": 444,
    "n_seeds_absent_from_edges": 19,
    "n_seeds_receive_only": 12,
    # The brief says "16 weakly connected components ... plus the 19 isolated
    # seeds", so 16 counts components of size >= 2 and the total is 35.
    "n_components_multi": 16,
    "n_isolated_seeds": 19,
    # 354 counts nodes that have a traced inflow; nodes with in_sum == 0 and
    # out_sum > 0 (seeds, mostly) trivially "send more than they receive".
    "n_sent_exceeds_received": 354,
    "n_pass_ratio_band": 72,
    "min_amount_kzt": 5000,
}

PERCENTILES = [0.50, 0.75, 0.90, 0.95, 0.99]


class Report:
    """Collects lines for both stdout and the markdown file."""

    def __init__(self) -> None:
        self.lines: list[str] = []
        self.mismatches: list[str] = []

    def h(self, text: str, level: int = 2) -> None:
        self.lines.append("")
        self.lines.append("#" * level + " " + text)
        self.lines.append("")

    def p(self, text: str = "") -> None:
        self.lines.append(text)

    def check(self, label: str, actual, expected) -> bool:
        """Record an announced-fact check. Never raises; mismatches are loud."""
        ok = actual == expected
        mark = "OK" if ok else "**MISMATCH**"
        self.p(f"| {label} | {expected} | {actual} | {mark} |")
        if not ok:
            self.mismatches.append(f"{label}: expected {expected}, found {actual}")
        return ok

    def table(self, header: list[str]) -> None:
        self.p("| " + " | ".join(header) + " |")
        self.p("|" + "|".join(["---"] * len(header)) + "|")

    def render(self) -> str:
        return "\n".join(self.lines) + "\n"


def _fmt_kzt(x: float) -> str:
    return f"{x:,.0f}"


def _node_flows(ds: Dataset) -> pd.DataFrame:
    """Per-node in/out degree and turnover, over all gids in nodes.parquet."""
    e = ds.edges
    out = e.groupby("src").agg(
        out_deg=("dst", "nunique"), out_sum=("sum_kzt", "sum"), n_tx_out=("n_tx", "sum")
    )
    inn = e.groupby("dst").agg(
        in_deg=("src", "nunique"), in_sum=("sum_kzt", "sum"), n_tx_in=("n_tx", "sum")
    )
    df = ds.nodes.set_index("gid").join(out).join(inn)
    for col in ["out_deg", "out_sum", "n_tx_out", "in_deg", "in_sum", "n_tx_in"]:
        df[col] = df[col].fillna(0)
    df[["out_deg", "in_deg", "n_tx_out", "n_tx_in"]] = df[
        ["out_deg", "in_deg", "n_tx_out", "n_tx_in"]
    ].astype("int64")
    # pass_ratio is only meaningful where inflow is real; seeds' inflow is
    # understated by construction (outgoing-only export), so it is excluded.
    reliable = (~df["is_seed"]) & (df["in_sum"] > 0)
    df["pass_ratio"] = np.where(reliable, df["out_sum"] / df["in_sum"].replace(0, np.nan), np.nan)
    return df.reset_index()


def _components(ds: Dataset) -> pd.DataFrame:
    """Weakly connected components over ALL gids, isolated seeds included."""
    import networkx as nx

    g = nx.Graph()
    g.add_nodes_from(ds.nodes["gid"].tolist())
    g.add_edges_from(zip(ds.edges["src"], ds.edges["dst"]))
    seeds = set(ds.seeds)
    comps = sorted(
        (sorted(c) for c in nx.connected_components(g)),
        key=lambda c: (-len(c), c[0]),
    )
    return pd.DataFrame(
        {
            "component_id": range(len(comps)),
            "n_nodes": [len(c) for c in comps],
            "n_seed": [len(seeds.intersection(c)) for c in comps],
        }
    )


def profile(ds: Dataset) -> tuple[Report, pd.DataFrame]:
    r = Report()
    nodes, edges, tx = ds.nodes, ds.edges, ds.tx
    seeds = set(ds.seeds)
    flows = _node_flows(ds)

    r.p("# Data profile report — Money Graph")
    r.p()
    r.p("Generated by `python -m moneygraph.profile`. Read-only pass over "
        "`data/`; nothing here modifies the organizers' files.")

    # ---------------------------------------------------------------- volumes
    r.h("1. Announced facts vs. actual data")
    r.table(["Fact", "Announced", "Actual", "Status"])
    r.check("nodes", len(nodes), EXPECTED["n_nodes"])
    r.check("edges", len(edges), EXPECTED["n_edges"])
    r.check("transactions", len(tx), EXPECTED["n_tx"])
    r.check("seeds", int(nodes["is_seed"].sum()), EXPECTED["n_seeds"])

    hops = nodes["depth"].value_counts().sort_index().to_dict()
    r.check("hop distribution", {int(k): int(v) for k, v in hops.items()},
            EXPECTED["hop_distribution"])

    edge_turnover = float(edges["sum_kzt"].sum())
    tx_turnover = float(tx["sum_kzt"].sum())
    r.check("turnover from edges (KZT)", round(edge_turnover), EXPECTED["total_turnover_kzt"])
    r.check("turnover from transactions (KZT)", round(tx_turnover), EXPECTED["total_turnover_kzt"])
    r.check("edges turnover == transactions turnover",
            round(edge_turnover, 2) == round(tx_turnover, 2), True)

    max_depth = ds.max_depth
    truncated = flows[(flows["depth"] == max_depth) & (flows["out_deg"] == 0)]
    r.check(f"depth=={max_depth} nodes with zero outgoing edges",
            len(truncated), EXPECTED["n_truncated"])

    in_edges = set(edges["src"]).union(edges["dst"])
    seeds_absent = sorted(seeds - in_edges)
    r.check("seeds absent from edges entirely", len(seeds_absent),
            EXPECTED["n_seeds_absent_from_edges"])

    senders = set(edges["src"])
    seeds_receive_only = sorted(s for s in seeds if s in in_edges and s not in senders)
    r.check("seeds appearing only as recipients", len(seeds_receive_only),
            EXPECTED["n_seeds_receive_only"])

    comps = _components(ds)
    r.check("weakly connected components of size >= 2",
            int((comps["n_nodes"] >= 2).sum()), EXPECTED["n_components_multi"])
    r.check("isolated seeds (components of size 1)",
            int((comps["n_nodes"] == 1).sum()), EXPECTED["n_isolated_seeds"])

    # Restricted to nodes with a traced inflow: without that restriction the
    # count is 377, because a node with in_sum == 0 trivially sends more.
    sent_exceeds = int(((flows["in_sum"] > 0) & (flows["out_sum"] > flows["in_sum"])).sum())
    r.check("nodes with in_sum > 0 whose sent amount exceeds received", sent_exceeds,
            EXPECTED["n_sent_exceeds_received"])
    r.p(f"| (same, without the in_sum > 0 restriction) | — | "
        f"{int((flows['out_sum'] > flows['in_sum']).sum())} | context |")

    # The brief's "~72 nodes with pass-through 0.8-1.2" counts the raw out/in
    # ratio including seeds. Our pass_ratio excludes seeds (their inflow is
    # understated), which drops the count to 70. Both are reported.
    raw_ratio = np.where(flows["in_sum"] > 0,
                         flows["out_sum"] / flows["in_sum"].replace(0, np.nan), np.nan)
    r.check("nodes with raw out/in ratio in [0.8, 1.2] (seeds included)",
            int(pd.Series(raw_ratio).between(0.8, 1.2).sum()), EXPECTED["n_pass_ratio_band"])
    r.p(f"| (same band, seeds excluded — our `pass_ratio`) | — | "
        f"{int(flows['pass_ratio'].between(0.8, 1.2).sum())} | context |")

    r.check("minimum transaction amount (KZT)", float(tx["sum_kzt"].min()) >= EXPECTED["min_amount_kzt"], True)

    # ------------------------------------------------------- data integrity
    r.h("2. Integrity of the three files")
    self_loops = edges[edges["src"] == edges["dst"]]
    dup_pairs = int(edges.duplicated(subset=["src", "dst"]).sum())
    agg = tx.groupby(["src", "dst"]).agg(s=("sum_kzt", "sum"), c=("sum_kzt", "size")).reset_index()
    merged = edges.merge(agg, on=["src", "dst"], how="outer", indicator=True)
    pairs_match = bool((merged["_merge"] == "both").all())
    sum_match = bool(np.allclose(merged["sum_kzt"], merged["s"], equal_nan=True))
    ntx_match = bool((merged["n_tx"] == merged["c"]).all())
    gids_in_edges_not_in_nodes = sorted(in_edges - set(nodes["gid"]))

    r.table(["Check", "Result"])
    r.p(f"| self-loops (src == dst) | {len(self_loops)} |")
    r.p(f"| duplicate (src, dst) pairs in edges | {dup_pairs} |")
    r.p(f"| every edge pair present in transactions and vice versa | {pairs_match} |")
    r.p(f"| per-pair transaction sum reproduces `edges.sum_kzt` | {sum_match} |")
    r.p(f"| per-pair transaction count reproduces `edges.n_tx` | {ntx_match} |")
    r.p(f"| gids in edges but missing from nodes.parquet | {len(gids_in_edges_not_in_nodes)} |")
    r.p(f"| duplicate gids in nodes.parquet | {int(nodes['gid'].duplicated().sum())} |")
    r.p(f"| date range | {tx['date'].min().date()} — {tx['date'].max().date()} |")
    r.p(f"| min / max transaction amount (KZT) | {_fmt_kzt(tx['sum_kzt'].min())} / {_fmt_kzt(tx['sum_kzt'].max())} |")
    r.p(f"| transactions below the 5,000 KZT threshold | {int((tx['sum_kzt'] < 5000).sum())} |")

    # --------------------------------------------------- the depth semantics
    r.h("3. What `depth` means, and the cut-off frontier")
    edge_depth = edges.merge(
        nodes.rename(columns={"gid": "src", "depth": "src_depth"})[["src", "src_depth"]], on="src"
    ).merge(
        nodes.rename(columns={"gid": "dst", "depth": "dst_depth"})[["dst", "dst_depth"]], on="dst"
    )
    matches_src = int((edge_depth["depth"] == edge_depth["src_depth"]).sum())
    matches_dst = int((edge_depth["depth"] == edge_depth["dst_depth"]).sum())
    r.p(f"- `edges.depth` equals the **source's** hop for {matches_src}/{len(edge_depth)} edges.")
    r.p(f"- `edges.depth` equals the **destination's** hop for {matches_dst}/{len(edge_depth)} edges.")
    interp = "the destination's hop" if matches_dst > matches_src else "the source's hop"
    r.p(f"- Interpretation used downstream: `edges.depth` is **{interp}**.")
    other = len(edge_depth) - max(matches_src, matches_dst)
    r.p(f"- The remaining **{other}** edges point at a destination discovered "
        f"*earlier* (at a lower hop), so their `depth` is the hop at which the "
        f"edge was found, not the destination's own hop. `depth` on an edge is "
        f"therefore a discovery marker and is not used for any role decision; "
        f"node `depth` from `nodes.parquet` is.")
    r.p()
    deep_with_out = flows[(flows["depth"] == max_depth) & (flows["out_deg"] > 0)]
    r.p(f"- MAX_DEPTH read from the data: **{max_depth}**.")
    r.p(f"- Nodes at depth {max_depth}: **{int((nodes['depth'] == max_depth).sum())}**, "
        f"of which **{len(deep_with_out)}** do have outgoing edges.")
    if len(deep_with_out):
        tgt_depths = edges[edges["src"].isin(set(deep_with_out['gid']))].merge(
            nodes.rename(columns={"gid": "dst", "depth": "dst_depth"})[["dst", "dst_depth"]], on="dst"
        )["dst_depth"].value_counts().sort_index().to_dict()
        r.p(f"  Their outgoing edges point to nodes at depths {tgt_depths} — i.e. back to "
            f"nodes already discovered earlier, not to new hop-5 nodes.")
    r.p(f"- Consequence: for depth-{max_depth} nodes outflow is **unknown, not zero**. "
        f"`terminal` must never be assigned there (guideline §8.2).")

    # ------------------------------------------------------- seed peculiarity
    r.h("4. Seeds")
    seed_flows = flows[flows["is_seed"]]
    r.p(f"- Seeds: **{len(seed_flows)}**; with no edge at all: **{len(seeds_absent)}**; "
        f"appearing only as recipients: **{len(seeds_receive_only)}**.")
    seed_pass = seed_flows[seed_flows["in_sum"] > 0]
    if len(seed_pass):
        raw_ratio = seed_pass["out_sum"] / seed_pass["in_sum"]
        r.p(f"- Among seeds that do receive something, raw out/in ratio runs "
            f"{raw_ratio.min():.2f} – {raw_ratio.max():.2f} (median {raw_ratio.median():.2f}). "
            f"This is an artifact of the outgoing-only export, not behaviour: seed inflows "
            f"from outside the sample are missing. `pass_ratio` is therefore NaN for seeds.")
    r.p(f"- Seed outgoing turnover: {_fmt_kzt(seed_flows['out_sum'].sum())} KZT "
        f"({100 * seed_flows['out_sum'].sum() / edge_turnover:.1f}% of all turnover).")

    # ---------------------------------------------------------- components
    r.h("5. Weakly connected components")
    r.table(["component_id", "n_nodes", "n_seed"])
    for row in comps.head(20).itertuples(index=False):
        r.p(f"| {row.component_id} | {row.n_nodes} | {row.n_seed} |")
    if len(comps) > 20:
        r.p(f"| … | {len(comps) - 20} more | |")
    r.p()
    r.p(f"- Components of size 1: **{int((comps['n_nodes'] == 1).sum())}** "
        f"(the isolated seeds); of size >= 2: **{int((comps['n_nodes'] >= 2).sum())}**.")
    r.p(f"- Components with more than one seed: **{int((comps['n_seed'] > 1).sum())}**.")

    # ---------------------------------------------------------- distributions
    r.h("6. Distributions — the basis for every threshold in `config.yaml`")
    dist_cols = ["in_deg", "out_deg", "in_sum", "out_sum", "pass_ratio"]
    desc = flows[dist_cols].quantile(PERCENTILES)
    r.table(["metric", "p50", "p75", "p90", "p95", "p99", "max"])
    for col in dist_cols:
        vals = [desc.loc[q, col] for q in PERCENTILES]
        mx = flows[col].max()
        fmt = (lambda v: f"{v:,.0f}") if col in ("in_sum", "out_sum") else (lambda v: f"{v:.2f}")
        r.p("| " + col + " | " + " | ".join(fmt(v) for v in vals) + f" | {fmt(mx)} |")
    r.p()
    r.p("Non-zero-only percentiles (the zeros are structural: leaves have no "
        "outflow, seeds no traced inflow):")
    r.table(["metric", "n>0", "p50", "p75", "p90", "p95", "p99"])
    for col in ["in_deg", "out_deg"]:
        nz = flows.loc[flows[col] > 0, col]
        r.p(f"| {col} | {len(nz)} | " + " | ".join(f"{nz.quantile(q):.0f}" for q in PERCENTILES) + " |")

    # counts that the role gates will produce, at the guideline's starting values
    r.h("7. Sanity of the starting thresholds (guideline §8.2)")
    pass_ratio = flows["pass_ratio"]
    r.table(["Gate at starting threshold", "Candidate nodes"])
    r.p(f"| in_deg >= 5 (consolidator) | {int((flows['in_deg'] >= 5).sum())} |")
    r.p(f"| in_deg >= 10 (strong consolidator) | {int((flows['in_deg'] >= 10).sum())} |")
    r.p(f"| out_deg >= 10 (distributor) | {int((flows['out_deg'] >= 10).sum())} |")
    r.p(f"| out_deg >= 10 and out_deg >= 3*max(in_deg,1) | "
        f"{int(((flows['out_deg'] >= 10) & (flows['out_deg'] >= 3 * flows['in_deg'].clip(lower=1))).sum())} |")
    r.p(f"| out_deg >= 50 (strong distributor) | {int((flows['out_deg'] >= 50).sum())} |")
    r.p(f"| pass_ratio in [0.8, 1.2] (transit) | {int(pass_ratio.between(0.8, 1.2).sum())} |")
    r.p(f"| pass_ratio <= 0.1 and depth < MAX_DEPTH and in_sum > 0 (terminal) | "
        f"{int(((flows['pass_ratio'] <= 0.1) & (flows['depth'] < max_depth) & (flows['in_sum'] > 0)).sum())} |")
    r.p(f"| in_deg between 8 and 24 (brief: 'many payers') | "
        f"{int(flows['in_deg'].between(8, 24).sum())} |")
    r.p(f"| out_deg between 60 and 116 (brief: 'many recipients') | "
        f"{int(flows['out_deg'].between(60, 116).sum())} |")

    # ------------------------------------------------------------ mismatches
    r.h("8. Mismatches to act on")
    if r.mismatches:
        for m in r.mismatches:
            r.p(f"- **{m}**")
        r.p()
        r.p("Per guideline §0: the organizers' files win. Update `guideline.md` "
            "and `config.yaml` to match the numbers above.")
    else:
        r.p("None. Every announced fact reproduces from the files as given.")

    return r, flows


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Phase 0 data profile")
    ap.add_argument("--data", default="data", help="folder with the parquet files")
    ap.add_argument("--out", default="outputs", help="where to write profile_report.md")
    a = ap.parse_args(argv)

    ds = load_dataset(a.data)
    report, flows = profile(ds)

    out_dir = Path(a.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    text = report.render()
    (out_dir / "profile_report.md").write_text(text, encoding="utf-8")
    print(text)
    print(f"[profile] written to {out_dir / 'profile_report.md'}")
    if report.mismatches:
        print(f"[profile] {len(report.mismatches)} MISMATCH(ES) — see section 8.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
