"""Phase 0 data profiling (guideline §3).

Prints a report and writes ``outputs/profile_report.md``. Every fact the brief
announces is checked against the actual files; a mismatch is reported loudly
rather than raised, because the point of this stage is to *learn* what the data
really looks like before any threshold is chosen.

The percentile tables at the end are what ``config.yaml`` thresholds are derived
from, so this module must run before any threshold is touched.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd

from .io import Dataset, load_config, load_dataset

# The announced facts live in config.yaml -> `expected`, so this module holds
# no numeric literals and the hardcoding guard in tests/ stays meaningful.
PERCENTILES = [0.50, 0.75, 0.90, 0.95, 0.99]


class Report:
    """Collects lines for both stdout and the markdown file."""

    def __init__(self) -> None:
        self.lines: list[str] = []
        self.mismatches: list[str] = []

    def h(self, text: str, level: int = 2) -> None:
        self.lines.append("")
        self.lines.append("#" * level + " " + text)
        self.lines.append("")

    def p(self, text: str = "") -> None:
        self.lines.append(text)

    def check(self, label: str, actual, expected) -> bool:
        """Record an announced-fact check. Never raises; mismatches are loud."""
        ok = actual == expected
        mark = "OK" if ok else "**MISMATCH**"
        self.p(f"| {label} | {expected} | {actual} | {mark} |")
        if not ok:
            self.mismatches.append(f"{label}: expected {expected}, found {actual}")
        return ok

    def table(self, header: list[str]) -> None:
        self.p("| " + " | ".join(header) + " |")
        self.p("|" + "|".join(["---"] * len(header)) + "|")

    def render(self) -> str:
        return "\n".join(self.lines) + "\n"


def _fmt_kzt(x: float) -> str:
    return f"{x:,.0f}"


def _node_flows(ds: Dataset) -> pd.DataFrame:
    """Per-node in/out degree and turnover, over all gids in nodes.parquet."""
    e = ds.edges
    out = e.groupby("src").agg(
        out_deg=("dst", "nunique"), out_sum=("sum_kzt", "sum"), n_tx_out=("n_tx", "sum")
    )
    inn = e.groupby("dst").agg(
        in_deg=("src", "nunique"), in_sum=("sum_kzt", "sum"), n_tx_in=("n_tx", "sum")
    )
    df = ds.nodes.set_index("gid").join(out).join(inn)
    for col in ["out_deg", "out_sum", "n_tx_out", "in_deg", "in_sum", "n_tx_in"]:
        df[col] = df[col].fillna(0)
    df[["out_deg", "in_deg", "n_tx_out", "n_tx_in"]] = df[
        ["out_deg", "in_deg", "n_tx_out", "n_tx_in"]
    ].astype("int64")
    # pass_ratio is only meaningful where inflow is real; seeds' inflow is
    # understated by construction (outgoing-only export), so it is excluded.
    reliable = (~df["is_seed"]) & (df["in_sum"] > 0)
    df["pass_ratio"] = np.where(reliable, df["out_sum"] / df["in_sum"].replace(0, np.nan), np.nan)
    return df.reset_index()


def _components(ds: Dataset) -> pd.DataFrame:
    """Weakly connected components over ALL gids, isolated seeds included."""
    import networkx as nx

    g = nx.Graph()
    g.add_nodes_from(ds.nodes["gid"].tolist())
    g.add_edges_from(zip(ds.edges["src"], ds.edges["dst"]))
    seeds = set(ds.seeds)
    comps = sorted(
        (sorted(c) for c in nx.connected_components(g)),
        key=lambda c: (-len(c), c[0]),
    )
    return pd.DataFrame(
        {
            "component_id": range(len(comps)),
            "n_nodes": [len(c) for c in comps],
            "n_seed": [len(seeds.intersection(c)) for c in comps],
        }
    )


def profile(ds: Dataset, cfg: dict | None = None) -> tuple[Report, pd.DataFrame]:
    """Profile the dataset against the announced facts in `cfg["expected"]`."""
    cfg = cfg if cfg is not None else load_config()
    expected = dict(cfg.get("expected") or {})
    r = Report()
    # The announced facts describe the organizers' export. When the tool is
    # pointed at a different file set, checking them would produce a wall of
    # meaningless mismatches, so the fact-check is skipped and the report says
    # so. The distributions in §6 are computed from whatever was loaded and
    # remain the basis for every threshold either way.
    facts_apply = bool(expected) and expected.get("n_nodes") == len(ds.nodes)
    nodes, edges, tx = ds.nodes, ds.edges, ds.tx
    seeds = set(ds.seeds)
    flows = _node_flows(ds)

    r.p("# Data profile report — Money Graph")
    r.p()
    r.p("Generated by `python -m moneygraph.profile`. Read-only pass over "
        "`data/`; nothing here modifies the organizers' files.")

    # ------------------------------------------------------------ provenance
    prov = getattr(ds, "provenance", {}) or {}
    if prov:
        r.h("0. What was loaded")
        r.table(["Canonical table", "Source file"])
        for kind, name in (prov.get("used") or {}).items():
            r.p(f"| {kind} | `{name}` |")
        files = prov.get("files") or []
        if files:
            r.p()
            r.p("Column mapping (how each input column was resolved):")
            r.table(["File", "Canonical field", "Column", "Resolved by"])
            for f in files:
                for canonical, col in (f.get("mapping") or {}).items():
                    r.p(f"| {f['file']} | {canonical} | `{col}` | "
                        f"{(f.get('resolved_by') or {}).get(canonical, '?')} |")
        if prov.get("derived"):
            r.p()
            r.p("**Derived, not supplied:**")
            for d in prov["derived"]:
                r.p(f"- {d}")
        if prov.get("notes"):
            r.p()
            r.p("Notes from ingestion:")
            for n in prov["notes"]:
                r.p(f"- {n}")

    # ---------------------------------------------------------------- volumes
    if not facts_apply:
        r.h("1. Announced facts")
        r.p("Skipped: this input does not match the shape of the organizers' "
            "export described in `config.yaml -> expected` "
            f"({len(ds.nodes)} nodes loaded, {expected.get('n_nodes', 'n/a')} "
            "announced). The checks below and the distributions in §6 are "
            "computed from the data actually loaded.")
        return _profile_rest(r, ds, cfg, flows, expected)

    r.h("1. Announced facts vs. actual data")
    r.table(["Fact", "Announced", "Actual", "Status"])
    r.check("nodes", len(nodes), expected["n_nodes"])
    r.check("edges", len(edges), expected["n_edges"])
    r.check("transactions", len(tx), expected["n_tx"])
    r.check("seeds", int(nodes["is_seed"].sum()), expected["n_seeds"])

    hops = nodes["depth"].value_counts().sort_index().to_dict()
    r.check("hop distribution", {int(k): int(v) for k, v in hops.items()},
            expected["hop_distribution"])

    edge_turnover = float(edges["sum_kzt"].sum())
    tx_turnover = float(tx["sum_kzt"].sum())
    r.check("turnover from edges (KZT)", round(edge_turnover), expected["total_turnover_kzt"])
    r.check("turnover from transactions (KZT)", round(tx_turnover), expected["total_turnover_kzt"])
    r.check("edges turnover == transactions turnover",
            round(edge_turnover, 2) == round(tx_turnover, 2), True)

    max_depth = ds.max_depth
    truncated = flows[(flows["depth"] == max_depth) & (flows["out_deg"] == 0)]
    r.check(f"depth=={max_depth} nodes with zero outgoing edges",
            len(truncated), expected["n_truncated"])

    in_edges = set(edges["src"]).union(edges["dst"])
    seeds_absent = sorted(seeds - in_edges)
    r.check("seeds absent from edges entirely", len(seeds_absent),
            expected["n_seeds_absent_from_edges"])

    senders = set(edges["src"])
    seeds_receive_only = sorted(s for s in seeds if s in in_edges and s not in senders)
    r.check("seeds appearing only as recipients", len(seeds_receive_only),
            expected["n_seeds_receive_only"])

    comps = _components(ds)
    r.check("weakly connected components of size >= 2",
            int((comps["n_nodes"] >= 2).sum()), expected["n_components_multi"])
    r.check("isolated seeds (components of size 1)",
            int((comps["n_nodes"] == 1).sum()), expected["n_isolated_seeds"])

    # Restricted to nodes with a traced inflow: without that restriction the
    # count is 377, because a node with in_sum == 0 trivially sends more.
    sent_exceeds = int(((flows["in_sum"] > 0) & (flows["out_sum"] > flows["in_sum"])).sum())
    r.check("nodes with in_sum > 0 whose sent amount exceeds received", sent_exceeds,
            expected["n_sent_exceeds_received"])
    r.p(f"| (same, without the in_sum > 0 restriction) | — | "
        f"{int((flows['out_sum'] > flows['in_sum']).sum())} | context |")

    # The brief's "~72 nodes with pass-through 0.8-1.2" counts the raw out/in
    # ratio including seeds. Our pass_ratio excludes seeds (their inflow is
    # understated), which drops the count to 70. Both are reported.
    raw_ratio = np.where(flows["in_sum"] > 0,
                         flows["out_sum"] / flows["in_sum"].replace(0, np.nan), np.nan)
    lo, hi = expected["pass_ratio_band"]
    r.check(f"nodes with raw out/in ratio in [{lo}, {hi}] (seeds included)",
            int(pd.Series(raw_ratio).between(lo, hi).sum()), expected["n_pass_ratio_band"])
    r.p(f"| (same band, seeds excluded — our `pass_ratio`) | — | "
        f"{int(flows['pass_ratio'].between(lo, hi).sum())} | context |")

    r.check(f"minimum transaction amount >= {expected['min_amount_kzt']:,} KZT",
            float(tx["sum_kzt"].min()) >= expected["min_amount_kzt"], True)

    return _profile_rest(r, ds, cfg, flows, expected)


def _profile_rest(r: Report, ds: Dataset, cfg: dict, flows: pd.DataFrame,
                  expected: dict) -> tuple[Report, pd.DataFrame]:
    """Sections 2-8: everything that does not depend on the announced facts."""
    nodes, edges, tx = ds.nodes, ds.edges, ds.tx
    seeds = set(ds.seeds)
    max_depth = ds.max_depth
    edge_turnover = float(edges["sum_kzt"].sum())
    in_edges = set(edges["src"]).union(edges["dst"])
    seeds_absent = sorted(seeds - in_edges)
    senders = set(edges["src"])
    seeds_receive_only = sorted(s for s in seeds if s in in_edges and s not in senders)
    comps = _components(ds)

    # ------------------------------------------------------- data integrity
    r.h("2. Integrity of the loaded tables")
    self_loops = edges[edges["src"] == edges["dst"]]
    dup_pairs = int(edges.duplicated(subset=["src", "dst"]).sum())
    if tx.empty:
        pairs_match = sum_match = ntx_match = "n/a (no transaction file)"
    else:
        agg = (tx.groupby(["src", "dst"])
                 .agg(s=("sum_kzt", "sum"), c=("sum_kzt", "size")).reset_index())
        merged = edges.merge(agg, on=["src", "dst"], how="outer", indicator=True)
        pairs_match = bool((merged["_merge"] == "both").all())
        sum_match = bool(np.allclose(merged["sum_kzt"], merged["s"], equal_nan=True))
        ntx_match = bool((merged["n_tx"] == merged["c"]).all())
    gids_in_edges_not_in_nodes = sorted(in_edges - set(nodes["gid"]))

    r.table(["Check", "Result"])
    r.p(f"| self-loops (src == dst) | {len(self_loops)} |")
    r.p(f"| duplicate (src, dst) pairs in edges | {dup_pairs} |")
    r.p(f"| every edge pair present in transactions and vice versa | {pairs_match} |")
    r.p(f"| per-pair transaction sum reproduces `edges.sum_kzt` | {sum_match} |")
    r.p(f"| per-pair transaction count reproduces `edges.n_tx` | {ntx_match} |")
    r.p(f"| gids in edges but missing from nodes.parquet | {len(gids_in_edges_not_in_nodes)} |")
    r.p(f"| duplicate gids in nodes.parquet | {int(nodes['gid'].duplicated().sum())} |")
    if tx.empty:
        r.p("| date range | n/a (no transaction file supplied) |")
        r.p(f"| min / max edge amount (KZT) | {_fmt_kzt(edges['sum_kzt'].min())} / "
            f"{_fmt_kzt(edges['sum_kzt'].max())} |")
    else:
        r.p(f"| date range | {tx['date'].min().date()} — {tx['date'].max().date()} |")
        r.p(f"| min / max transaction amount (KZT) | {_fmt_kzt(tx['sum_kzt'].min())} / "
            f"{_fmt_kzt(tx['sum_kzt'].max())} |")
    floor = expected.get("min_amount_kzt")
    if floor and not tx.empty:
        r.p(f"| transactions below the {floor:,} KZT threshold | "
            f"{int((tx['sum_kzt'] < floor).sum())} |")

    # --------------------------------------------------- the depth semantics
    r.h("3. What `depth` means, and the cut-off frontier")
    edge_depth = edges.merge(
        nodes.rename(columns={"gid": "src", "depth": "src_depth"})[["src", "src_depth"]], on="src"
    ).merge(
        nodes.rename(columns={"gid": "dst", "depth": "dst_depth"})[["dst", "dst_depth"]], on="dst"
    )
    matches_src = int((edge_depth["depth"] == edge_depth["src_depth"]).sum())
    matches_dst = int((edge_depth["depth"] == edge_depth["dst_depth"]).sum())
    r.p(f"- `edges.depth` equals the **source's** hop for {matches_src}/{len(edge_depth)} edges.")
    r.p(f"- `edges.depth` equals the **destination's** hop for {matches_dst}/{len(edge_depth)} edges.")
    interp = "the destination's hop" if matches_dst > matches_src else "the source's hop"
    r.p(f"- Interpretation used downstream: `edges.depth` is **{interp}**.")
    other = len(edge_depth) - max(matches_src, matches_dst)
    r.p(f"- The remaining **{other}** edges point at a destination discovered "
        f"*earlier* (at a lower hop), so their `depth` is the hop at which the "
        f"edge was found, not the destination's own hop. `depth` on an edge is "
        f"therefore a discovery marker and is not used for any role decision; "
        f"node `depth` from `nodes.parquet` is.")
    r.p()
    deep_with_out = flows[(flows["depth"] == max_depth) & (flows["out_deg"] > 0)]
    r.p(f"- MAX_DEPTH read from the data: **{max_depth}**.")
    r.p(f"- Nodes at depth {max_depth}: **{int((nodes['depth'] == max_depth).sum())}**, "
        f"of which **{len(deep_with_out)}** do have outgoing edges.")
    if len(deep_with_out):
        tgt_depths = edges[edges["src"].isin(set(deep_with_out['gid']))].merge(
            nodes.rename(columns={"gid": "dst", "depth": "dst_depth"})[["dst", "dst_depth"]], on="dst"
        )["dst_depth"].value_counts().sort_index().to_dict()
        r.p(f"  Their outgoing edges point to nodes at depths {tgt_depths} — i.e. back to "
            f"nodes already discovered earlier, not to new nodes beyond the frontier.")
    r.p(f"- Consequence: for depth-{max_depth} nodes outflow is **unknown, not zero**. "
        f"`terminal` is never assigned there (guideline §8.2).")

    # ------------------------------------------------------- seed peculiarity
    r.h("4. Seeds")
    seed_flows = flows[flows["is_seed"]]
    r.p(f"- Seeds: **{len(seed_flows)}**; with no edge at all: **{len(seeds_absent)}**; "
        f"appearing only as recipients: **{len(seeds_receive_only)}**.")
    seed_pass = seed_flows[seed_flows["in_sum"] > 0]
    if len(seed_pass):
        raw_ratio = seed_pass["out_sum"] / seed_pass["in_sum"]
        r.p(f"- Among seeds that do receive something, raw out/in ratio runs "
            f"{raw_ratio.min():.2f} – {raw_ratio.max():.2f} (median {raw_ratio.median():.2f}). "
            f"This is an artifact of the outgoing-only export, not behaviour: seed inflows "
            f"from outside the sample are missing. `pass_ratio` is therefore NaN for seeds.")
    share = (100 * seed_flows["out_sum"].sum() / edge_turnover) if edge_turnover else 0.0
    r.p(f"- Seed outgoing turnover: {_fmt_kzt(seed_flows['out_sum'].sum())} KZT "
        f"({share:.1f}% of all turnover).")

    # ---------------------------------------------------------- components
    r.h("5. Weakly connected components")
    r.table(["component_id", "n_nodes", "n_seed"])
    for row in comps.head(20).itertuples(index=False):
        r.p(f"| {row.component_id} | {row.n_nodes} | {row.n_seed} |")
    if len(comps) > 20:
        r.p(f"| … | {len(comps) - 20} more | |")
    r.p()
    r.p(f"- Components of size 1: **{int((comps['n_nodes'] == 1).sum())}** "
        f"(the isolated seeds); of size >= 2: **{int((comps['n_nodes'] >= 2).sum())}**.")
    r.p(f"- Components with more than one seed: **{int((comps['n_seed'] > 1).sum())}**.")

    # ---------------------------------------------------------- distributions
    r.h("6. Distributions — the basis for every threshold in `config.yaml`")
    dist_cols = ["in_deg", "out_deg", "in_sum", "out_sum", "pass_ratio"]
    desc = flows[dist_cols].quantile(PERCENTILES)
    r.table(["metric", "p50", "p75", "p90", "p95", "p99", "max"])
    for col in dist_cols:
        vals = [desc.loc[q, col] for q in PERCENTILES]
        mx = flows[col].max()
        fmt = (lambda v: f"{v:,.0f}") if col in ("in_sum", "out_sum") else (lambda v: f"{v:.2f}")
        r.p("| " + col + " | " + " | ".join(fmt(v) for v in vals) + f" | {fmt(mx)} |")
    r.p()
    r.p("Non-zero-only percentiles (the zeros are structural: leaves have no "
        "outflow, seeds no traced inflow):")
    r.table(["metric", "n>0", "p50", "p75", "p90", "p95", "p99"])
    for col in ["in_deg", "out_deg"]:
        nz = flows.loc[flows[col] > 0, col]
        r.p(f"| {col} | {len(nz)} | " + " | ".join(f"{nz.quantile(q):.0f}" for q in PERCENTILES) + " |")

    # counts that the role gates will produce, at the guideline's starting values
    r.h("7. Candidate counts at the thresholds currently in `config.yaml`")
    rc = cfg["roles"]
    cons_min, cons_strong = rc["consolidator"]["min_payers"], rc["consolidator"]["strong_payers"]
    dist_min = rc["distributor"]["min_recipients"]
    dist_ratio, dist_strong = rc["distributor"]["fan_ratio"], rc["distributor"]["strong_recipients"]
    t_lo, t_hi = rc["transit"]["ratio_low"], rc["transit"]["ratio_high"]
    term_max = rc["terminal"]["max_pass"]
    pr = flows["pass_ratio"]

    r.table(["Gate", "Candidate nodes", "Share of graph"])

    def gate(label: str, mask) -> None:
        n = int(mask.sum())
        r.p(f"| {label} | {n} | {100 * n / len(flows):.1f}% |")

    gate(f"in_deg >= {cons_min} (consolidator)", flows["in_deg"] >= cons_min)
    gate(f"in_deg >= {cons_strong} (strong consolidator)", flows["in_deg"] >= cons_strong)
    gate(f"out_deg >= {dist_min} (distributor, fan-out only)", flows["out_deg"] >= dist_min)
    gate(f"out_deg >= {dist_min} and >= {dist_ratio}x in_deg (distributor gate)",
         (flows["out_deg"] >= dist_min)
         & (flows["out_deg"] >= dist_ratio * flows["in_deg"].clip(lower=1)))
    gate(f"out_deg >= {dist_strong} (strong distributor)", flows["out_deg"] >= dist_strong)
    gate(f"pass_ratio in [{t_lo}, {t_hi}] (transit)", pr.between(t_lo, t_hi))
    term_mask = (pr <= term_max) & (flows["depth"] < max_depth) & (flows["in_sum"] > 0)
    gate(f"pass_ratio <= {term_max}, depth < MAX_DEPTH, in_sum > 0 (terminal)", term_mask)
    r.p()
    dead_end = int((term_mask & (flows["out_deg"] == 0)).sum())
    r.p(f"The terminal gate is broad: **{int(term_mask.sum())}** nodes, of which "
        f"**{dead_end}** have no outgoing edge at all. Those were genuinely "
        f"expanded by the crawl and had nothing >= "
        f"{expected['min_amount_kzt']:,} KZT leaving them, so `terminal` is "
        f"correct but carries little information on its own. Priority must not "
        f"lean on it — hence the low role weight in `config.yaml`.")
    r.p()
    r.p(f"Degenerate-outcome watch (guideline §16): no gate above claims more "
        f"than a few percent of the graph except `terminal`, and none claims "
        f"zero nodes.")

    # ------------------------------------------------------------ mismatches
    r.h("8. Mismatches to act on")
    if r.mismatches:
        for m in r.mismatches:
            r.p(f"- **{m}**")
        r.p()
        r.p("Per guideline §0: the organizers' files win. Update `guideline.md` "
            "and `config.yaml` to match the numbers above.")
    else:
        r.p("None. Every announced fact reproduces from the files as given.")

    return r, flows


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Phase 0 data profile")
    ap.add_argument("--data", default="data", help="folder with the parquet files")
    ap.add_argument("--out", default="outputs", help="where to write profile_report.md")
    ap.add_argument("--config", default="config.yaml",
                    help="thresholds and announced facts")
    a = ap.parse_args(argv)

    cfg = load_config(a.config)
    ds = load_dataset(a.data, cfg)
    report, flows = profile(ds, cfg)

    out_dir = Path(a.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    text = report.render()
    (out_dir / "profile_report.md").write_text(text, encoding="utf-8")
    print(text)
    print(f"[profile] written to {out_dir / 'profile_report.md'}")
    if report.mismatches:
        print(f"[profile] {len(report.mismatches)} MISMATCH(ES) — see section 8.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
